language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - php --version
  - composer selfupdate
  - PHP_CURRENT='5.6'

script:
  - make test
  - '[ $(phpenv version-name) == "$PHP_CURRENT" ] || make test-upload'
  - make clean

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

notifications:
  webhooks:
    urls:
      - http://derricks.io/repositories/buildhook/
    on_success: always
    on_failure: always
    on_start: true
